# Quick Start - Scegli il tuo database e inizia subito!
# Copia questo file come docker-compose.yml e decommentare la sezione necessaria

version: '3.8'

services:
  # ==========================================
  # MYSQL - Decommenta questa sezione
  # ==========================================
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: changeme
  #     MYSQL_DATABASE: myapp
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # mysql_backup:
  #   image: db-backup-sidecar:latest
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_TYPE: mysql
  #     DB_HOST: mysql
  #     DB_USER: root
  #     DB_PASSWORD: changeme
  #     DB_NAME: all
  #   volumes:
  #     - ./backups:/backups
  #   command: ["run"]

  # ==========================================
  # POSTGRESQL - Decommenta questa sezione
  # ==========================================
  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_PASSWORD: changeme
  #     POSTGRES_DB: myapp

  # postgres_backup:
  #   image: db-backup-sidecar:latest
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_TYPE: postgres
  #     DB_HOST: postgres
  #     DB_USER: postgres
  #     DB_PASSWORD: changeme
  #   volumes:
  #     - ./backups:/backups
  #   command: ["run"]

  # ==========================================
  # MONGODB - Decommenta questa sezione
  # ==========================================
  # mongodb:
  #   image: mongo:7
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: changeme

  # mongodb_backup:
  #   image: db-backup-sidecar:latest
  #   depends_on:
  #     - mongodb
  #   environment:
  #     DB_TYPE: mongodb
  #     DB_HOST: mongodb
  #     DB_USER: admin
  #     DB_PASSWORD: changeme
  #     DB_AUTH_DB: admin
  #   volumes:
  #     - ./backups:/backups
  #   command: ["run"]

  # ==========================================
  # REDIS - Decommenta questa sezione
  # ==========================================
  # redis:
  #   image: redis:7-alpine
  #   command: redis-server --requirepass changeme

  # redis_backup:
  #   image: db-backup-sidecar:latest
  #   depends_on:
  #     - redis
  #   environment:
  #     DB_TYPE: redis
  #     DB_HOST: redis
  #     DB_PASSWORD: changeme
  #   volumes:
  #     - ./backups:/backups
  #   command: ["run"]

volumes:
  mysql_data:
  postgres_data:
  mongodb_data:
  redis_data:
